---
version: '2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 32181:32181
    expose:
      - 32181

  kafka:
    image: confluentinc/cp-kafka:3.2.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
    ports:
      - 29092:29092
    expose:
      - 29092

  schema-registry:
      image: confluentinc/cp-schema-registry:3.2.0
      environment:
        SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:32181
        SCHEMA_REGISTRY_HOST_NAME: schema-registry
        SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      depends_on:
        - zookeeper
        - kafka
      ports:
        - 8081:8081
      expose:
        - 8081

  hydra:
    image: pluralsight/hydra:0.9.5
    command: bash
    volumes:
      - /app
    ports:
      - 8088:8088
    expose:
      - 8088
    links:
      - kafka
      - schema-registry